KEEP_ALIVE_SEC: 240 
FARM_CICLE_MAX: 12  # 48 min
FARM_CICLE_MED: 8   # 32 min
FARM_CICLE_MIN: 4   # 16 min
WAIT_SEC: 1.5
WAIT_SIGN_IN: 15
SCROLL_DELAY: .03
MOVE_SEC: .2
HERO_STRIP_HEIGHT: 44
HERO_STRIP_DIVIDER: 6
HERO_FIRST_POS_Y: -260
HERO_TOTAL_HEIGHT: 255
TOTAL_HEROS: 15
TOTAL_SCREENS: 4